# SPDX-License-Identifier: GPL-3.0-or-later
# vim:foldmethod=marker
variables:
  # IMAGE_TAG is a Git branch/tag name from https://gitlab.nic.cz/knot/knot-resolver-ci
  # In general, keep it pointing to a tag - use a branch only for development.
  # More info in the knot-resolver-ci repository.
  IMAGE_TAG: v20240924
  IMAGE_PREFIX: $CI_REGISTRY/knot/knot-resolver-ci

image: $IMAGE_PREFIX/debian12-knot_3_3:$IMAGE_TAG

default:
  interruptible: true
  tags:
    - docker
    - linux
    - amd64

stages:
  - build
  - sanity
  - test
  - deploy
  - release
