# docs: {{{

docs:build:
  stage: build
  needs: []
  script:
    - git submodule update --init --recursive
    - pip3 install -U -r doc/requirements.txt
    - pip3 install -U sphinx_rtd_theme
    - meson build_doc -Ddoc=enabled
    - ninja -C build_doc doc
  artifacts:
    paths:
      - doc/html

# This job deploys the Knot Resolver documentation into the GitLab environment.
# https://gitlab.nic.cz/knot/knot-resolver/-/environments/folders/docs
docs:environment:
  stage: deploy
  needs:
    - docs:build
  script:
    - echo "Propagating 'doc/html' artifacts into GitLab's environment"
  artifacts:
    paths:
      - doc/html
  environment:
    name: docs/$CI_COMMIT_REF_NAME
    url: https://www.knot-resolver.cz/documentation/artifacts/$CI_JOB_ID/index.html

# This job deploys the Knot Resolver documentation to the GitLab pages.
# https://knot.pages.nic.cz/knot-resolver
docs:pages:
  stage: deploy
  needs:
    - docs:build
  script: mv doc/html public
  when: manual
  artifacts:
    paths:
      - public

# Pushes the documentation into a new branch of the website repository.
# https://gitlab.nic.cz/websites/knot-resolver.cz
docs:website:
  stage: release
  needs:
    - docs:build
  only:
    - tags
  when: manual
  variables:
  script:
    - "SRC_COMMIT_REF=\"$CI_COMMIT_TAG$CI_COMMIT_BRANCH$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME\""
    - "git clone \"https://gitlab-ci-token:$WEBSITE_DOCS_CI_TOKEN@$CI_SERVER_HOST:$CI_SERVER_PORT/websites/knot-resolver.cz.git\" website"
    - "cp --recursive --verbose \"doc/html\" \"website/content/documentation/$SRC_COMMIT_REF\""
    - cd website
    - "git checkout -b \"docs/$SRC_COMMIT_REF\""
    - "git add \"content/documentation/$SRC_COMMIT_REF\""
    - "git commit -m \"docs: $SRC_COMMIT_REF\""
    - "git push --force --set-upstream origin \"docs/$SRC_COMMIT_REF\""

# }}}